spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://192.168.1.88:3312/elevator?characterEncoding=UTF-8&useSSL=true
          username: scm
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        park:
          url: jdbc:mysql://192.168.1.88:3312/park?characterEncoding=UTF-8&useSSL=true
          username: scm
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        auth:
          url: jdbc:mysql://192.168.1.88:3312/ufast_auth_rel?characterEncoding=UTF-8&useSSL=true
          username: scm
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
#          schema: db/schema.sql # 配置则生效,自动初始化表结构
#          data: db/data.sql # 配置则生效,自动初始化数据
#          continue-on-error: true # 默认true,初始化失败是否继续
#          separator: ";" # sql默认分号分隔符
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
